apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-resource-deployment
  labels:
    app: user-resource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-resource
  template:
    metadata:
      labels:
        app: user-resource
    spec:
      containers:
      - name: user-resource
        image: docker.io/skullgnammer/user-resource:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "400Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-resource-service
spec:
  selector:
    app: user-resource
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080