spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: true
  application:
    name: user-resource
  datasource:
    url: jdbc:h2:mem:testdb

server:
  port: 8080
