name: Docker Publish

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: user-resource

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.5.4

      - name: Build with maven
        run: mvn spring-boot:build-image
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker
        run: docker push skullgnammer/user-resource:latest

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment-config.yaml
          kubectl rollout restart deployment/user-resource-deployment
